name: PrTitleSemanticLint
on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize, reopened]
jobs:
  Lint:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Ensure PR Title is Semantic
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
          npx --yes @coveo/is-pr-title-semantic
