name: Create release

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

permissions:
  contents: write
  # packages: write
  pull-requests: write

# concurrency:
#   group: 'packages'
#   cancel-in-progress: true

jobs:
  # release-please:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: google-github-actions/release-please-action@v3
  #       with:
  #         release-type: maven
  #         package-name: release-please-action
  # prepare:
  #   runs-on: ubuntu-latest
  #   environment: CD
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         ssh-key: ${{ secrets.DEPLOY_KEY }}
  #     - run: git fetch --all --tags
  #     - uses: actions/setup-node@v3
  #       with:
  #         registry-url: 'https://registry.npmjs.org'
  #         cache: 'npm'
  #         node-version: 18
  #     - name: Install
  #       run: npm ci
  #     - name: Setup Git
  #       run: |
  #         git config --global user.email action@github.com
  #         git config --global user.name GitHub Action
  #     - name: Bump Version
  #       run: npm run standard-version -- --commit-all
  #         git config --global user.name GitHub Action
  #     # - name: Push changes
  #     #   run: |
  #     #     git push --follow-tags origin master
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: mvn clean package

      - uses: google-github-actions/release-please-action@v3
        with:
          package-name: release-please-action
          default-branch: master
          pull-request-title-pattern: 'chore${scope}: release${component} ${version}'
          token: ${{ secrets.GITHUB_TOKEN }}

          # TODO: manually bump bersio

      # - run: mvn --batch-mode deploy
      #   if: ${{ steps.release.outputs.release_created }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
