name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: mvn clean package

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          package-name: release-please-action
          default-branch: master
          release-as: 2.55.0
          last-release-sha: 9e7688aa03e39497de08fdd4068c3e1e2b27c319
          pull-request-title-pattern: 'chore${scope}: release${component} ${version} [skip-ci]'
          token: ${{ secrets.RELEASE_KEY }}
          # TODO: include jar files as well
